version: '1.0'

services:
  - name: savvy-music-bot
    image: python:3.10
    replicas: 1
    command: ["bash", "-c", "pip install -r requirements.txt && python __main__.py"]
    env:
      - name: API_ID
        value: ""
      - name: API_HASH
        value: ""
      - name: BOT_TOKEN
       value: ""
      - name: MONGO_DB_URI
       value: ""
      - name: OWNER_ID
      value: ""
      - name: SESSION
      value: ""
      -name: 
      value:
      
    ports:
      - 8080:8080
